In [1]:
from joblib import dump, load
import numpy as np
model= load("WorthWhisperer.joblibe")

In [5]:
features = np.array([[0.009, 20, 4.31,1,0.6,9.575,3.2, 8.09, 2, 250, 15.9,396.6, 5.99]])
model.predict(features)

array([22.489])

In [8]:
features = np.array([[0.00522, 19, 3.31, 0, 0.45, 1.575, 68.2, 5.07, 3, 246, 14.3,394.7, 5.98]])
model.predict(features)

array([20.52])

In [11]:
features = np.array([[0.0762, 38, 5.31, 0, 1.53, 2.575, 75.6, 7.06, 1, 256, 14.7,336.9, 400.98]])
model.predict(features)

array([20.411])

In [12]:
features = np.array([[0.0762, 38, 555.31, 0, 1.53, 1.575, 75.6, 7.06, 1, 256, 444.7,366.9, 400.98]])
model.predict(features)

array([17.112])